### ISSUE TITLE
不兼容 ChestTracker 1.20.1

### ISSUE THREAD

**Issue by lgc2333** [reserveword/IMBlocker#15]
使用的是这个版本 https://github.com/JackFred2/ChestTracker/pull/94
文件是我自己用gh actions构建的 https://github.com/lgc2333/ChestTracker/actions/runs/5370776696

错误报告：[错误报告-2023-6-26_1.33.39.zip](https://github.com/JackFred2/ChestTracker/files/11860401/-2023-6-26_1.33.39.zip)

```txt
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-06-26 01:29:50
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_327.method_27523(String, int)" because "this.font" is null
	at io.github.cottonmc.cotton.gui.widget.WTextField.scrollCursorIntoView(WTextField.java:155)
	at io.github.cottonmc.cotton.gui.widget.WTextField.insertText(WTextField.java:389)
	at io.github.cottonmc.cotton.gui.widget.WTextField.onCharTyped(WTextField.java:369)
	at red.jackf.chesttracker.gui.widgets.WUpdatableTextField.onCharTyped(WUpdatableTextField.java:21)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.method_25400(CottonClientScreen.java:232)
	at io.github.reserveword.imblocker.FabricScreenInfo.charTyped(FabricScreenInfo.java:36)
	at io.github.reserveword.imblocker.IMCheckState.checkNonPrintable(IMCheckState.java:127)
	at io.github.reserveword.imblocker.IMCheckState.clientTick(IMCheckState.java:154)
	at io.github.reserveword.imblocker.IMBlockerFabric.lambda$onInitializeClient$0(IMBlockerFabric.java:25)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$dea000$fabric-lifecycle-events-v1$onStartTick(class_310.java:15017)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
```

**Comment by reserveword** [comment]
总之先拿try-catch包起来试试吧，看看新版4.0.1能不能用
另外，fabric版这类事情还真多啊，#16 也是差不多的问题
