### ISSUE TITLE
IMBlocker-v4.0.0-alpha5-mc1.20版本会和reply mod冲突

### ISSUE THREAD

**Issue by mark-jiang-1470** [reserveword/IMBlocker#16]
错误日志：

Time: 2023-07-01 00:48:18
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "com.replaymod.lib.de.johni0702.minecraft.gui.utils.lwjgl.ReadableDimension.getHeight()" because "this.lastRenderSize" is null
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScrollable.scrollY(AbstractGuiScrollable.java:165)
	at com.replaymod.replay.gui.screen.GuiReplayViewer$GuiReplayList.typeKey(GuiReplayViewer.java:439)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.lambda$charTyped$1(AbstractGuiScreen.java:286)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$7(ComposedGuiElement.java:82)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:58)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$5(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.forEach(ComposedGuiElement.java:42)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.charTyped(AbstractGuiScreen.java:286)
	at io.github.reserveword.imblocker.FabricScreenInfo.charTyped(FabricScreenInfo.java:36)
	at io.github.reserveword.imblocker.IMCheckState.checkNonPrintable(IMCheckState.java:127)
	at io.github.reserveword.imblocker.IMCheckState.clientTick(IMCheckState.java:154)
	at io.github.reserveword.imblocker.IMBlockerFabric.lambda$onInitializeClient$0(IMBlockerFabric.java:25)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at MC//net.minecraft.client.MinecraftClient.handler$bda000$fabric-lifecycle-events-v1$onStartTick(MinecraftClient.java:8017)
	at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.1/java.lang.reflect.Method.invoke(Method.java:568)
	at app//oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at app//oolloo.jlw.Wrapper.main(Wrapper.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScrollable.scrollY(AbstractGuiScrollable.java:165)
	at com.replaymod.replay.gui.screen.GuiReplayViewer$GuiReplayList.typeKey(GuiReplayViewer.java:439)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.lambda$charTyped$1(AbstractGuiScreen.java:286)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$7(ComposedGuiElement.java:82)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:58)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$5(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.forEach(ComposedGuiElement.java:42)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.charTyped(AbstractGuiScreen.java:286)
	at io.github.reserveword.imblocker.FabricScreenInfo.charTyped(FabricScreenInfo.java:36)
	at io.github.reserveword.imblocker.IMCheckState.checkNonPrintable(IMCheckState.java:127)
	at io.github.reserveword.imblocker.IMCheckState.clientTick(IMCheckState.java:154)
	at io.github.reserveword.imblocker.IMBlockerFabric.lambda$onInitializeClient$0(IMBlockerFabric.java:25)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at MC//net.minecraft.client.MinecraftClient.handler$bda000$fabric-lifecycle-events-v1$onStartTick(MinecraftClient.java:8017)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/XKRD红显3.0for1.20.zip, replaymod_lang
Stacktrace:
	at MC//net.minecraft.client.resource.ResourceReloadLogger.addReloadSection(ResourceReloadLogger.java:49)
	at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2413)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.1/java.lang.reflect.Method.invoke(Method.java:568)
	at app//oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at app//oolloo.jlw.Wrapper.main(Wrapper.java:53)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 277387816 bytes (264 MiB) / 788529152 bytes (752 MiB) up to 15359541248 bytes (14648 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x24dd
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Graphics card #1 name: OrayIddDriver Device
	Graphics card #1 vendor: Shanghai Best Oray Information Technology Co., Ltd.
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=17.1.58.818
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 130924.06
	Virtual memory used (MB): 58332.42
	Swap memory total (MB): 65536.00
	Swap memory used (MB): 313.64
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx14643m
	Fabric Mods: 
		antighost: AntiGhost 1.20-fabric0.83.0-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		appleskin: AppleSkin 2.5.0+mc1.20
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		architectury: Architectury 9.0.8
		betterstats: Better Statistics Screen 2.10.3+1.20.1
		bobby: Bobby 5.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a82
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b82
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		carpet: Carpet Mod 1.4.112+v230608
		chat_heads: Chat Heads 0.10.16
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		fabric-api: Fabric API 0.84.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		imblocker: IMBlocker 4.0.0-alpha
		inventoryhud: Inventory HUD + 3.4.13
		inventoryprofilesnext: Inventory Profiles Next 1.10.6
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		isometric-renders: Isometric Renders 0.4.4+1.20
			worldmesher: Worldmesher 0.3.0+1.20
		jade: Jade 11.1.4
		java: Java HotSpot(TM) 64-Bit Server VM 17
		libipn: libIPN 3.0.2
		litematica: Litematica 0.15.0
		lithium: Lithium 0.11.2
		malilib: MaLiLib 0.16.0
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.1.0
		morechathistory: MoreChatHistory 1.1.1
		mousetweaks: Mouse Tweaks 2.25
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		reeses-sodium-options: Reese's Sodium Options 1.5.1+mc1.20-build.74
		replaymod: Replay Mod 1.20.1-2.6.13
		roughlyenoughitems: Roughly Enough Items 12.0.625
			error_notifier: Error Notifier 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
		spyglass-improvements: Spyglass Improvements 1.4+mc1.20+fabric
		stackdeobfuscator: StackDeobfuscator 1.3.2+fabric.4bca927
			net_fabricmc_mapping-io: mapping-io 0.3.0
		starlight: Starlight 1.1.2+fabric.dbc156f
		syncmatica: Syncmatica 1.20.1-0.3.9
		tcdcommons: TCD Commons API 2.10.2+1.20.1
		tweakermore: TweakerMore 3.13.1
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
			conditional-mixin: conditional mixin 0.3.2
		tweakeroo: Tweakeroo 0.17.0
		xaerominimap: Xaero's Minimap 23.5.0
		xaeroworldmap: Xaero's World Map 1.30.6
	Loaded Shaderpack: ComplementaryShaders_v4.5-gama.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.20.1-Fabric 0.14.21
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/XKRD红显3.0for1.20.zip
	Current Language: zh_cn
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics

**Comment by mark-jiang-1470** [comment]
忘记说是什么情况下发生的问题了，是在开始菜单，点reply mod的回放中心，会崩溃

**Comment by reserveword** [comment]
总之先拿try-catch包起来试试吧，看看新版4.0.1能不能用
另外，fabric版这类事情还真多啊，#15 也是差不多的问题
