### ISSUE TITLE
鼠标任意键单击文本输入区域时会键入空白字符

### ISSUE THREAD

**Issue by AdminHcat** [reserveword/IMBlocker#22]
加载IMBlocker Mod后, 在部分模组文本输入框中，使用鼠标左中右键单击文本输入区域时会键入空白字符
Minecraft Fabric 1.20.1 
IMBlocker-v4.0.3-alpha-mc1.20

使用[Notebook](https://modrinth.com/mod/notebook) 测试
![测试](https://github.com/reserveword/IMBlocker/assets/50044729/92614e16-a918-4412-b791-0d14190e7ab4)

**Comment by Fiz-Victor** [comment]
这模组文本框选中的时候都会自动输入一个隐形字符，好像是为了检测文本框可否输入

**Comment by reserveword** [comment]
如果模组使用了自己实现的文本框就会出现这种情况。我正在考虑怎么解决。
目前可以关闭实验性选项来规避这个问题，fabric下需要clothconfig提供配置支持。

**Comment by reserveword** [comment]
希望能帮我统计一下哪些模组会出现这样的情况
现已知使用Architectury生成gui的模组和issue中提到的notebook这两个模组是会出现的

**Comment by Fiz-Victor** [comment]
> 希望能帮我统计一下哪些模组会出现这样的情况 现已知使用Architectury生成gui的模组和issue中提到的notebook这两个模组是会出现的

经过测试彗星端也会有这个bug

**Comment by reserveword** [comment]
> 经过测试彗星端也会有这个bug

彗星端是什么？最好能定位到mod

**Comment by Fiz-Victor** [comment]
https://github.com/MeteorDevelopment/meteor-client/

**Comment by reserveword** [comment]
更新了一个版本，rei、replaymod、notebook现在可以正常工作了。还有cotton、ftb、metetor相关的文本框没有测试过，@Fiz-Victor 希望能帮忙测试一下metetor

**Comment by Fiz-Victor** [comment]
现在rei还有点问题，shadow好像找不到方法了
```
[22:22:10] [Render thread/WARN]: Mixin apply for mod imblocker failed imblocker.mixins.json:ReiTextFieldMixin from mod imblocker -> me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method isFocused in imblocker.mixins.json:ReiTextFieldMixin from mod imblocker was not located in the target class me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget. Using refmap client-fabric-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method isFocused in imblocker.mixins.json:ReiTextFieldMixin from mod imblocker was not located in the target class me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget. Using refmap client-fabric-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:102) ~[meteor-client-0.5.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethod(Class.java:2673) ~[?:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:71) ~[RoughlyEnoughItems-12.0.634.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitializeClient(RoughlyEnoughItemsInitializer.java:57) ~[RoughlyEnoughItems-12.0.634.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy79.onInitializeClient(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
```

**Comment by reserveword** [comment]
> 现在rei还有点问题，shadow好像找不到方法了

能正常工作吗（正常启动游戏、rei的文本框正常输入中文）
使用的是什么版本的rei、fabric、minecraft？

**Comment by reserveword** [comment]
请确认在出现报错的情况下rei文本框的中文输入是否能正常工作，如果不能正常工作请附上环境信息（如：minecraft版本、fabric版本、fabric api版本、其他mod）

**Comment by Blalala6868** [comment]
> 更新了一个版本，rei、replaymod、notebook现在可以正常工作了。还有cotton、ftb、metetor相关的文本框没有测试过，@Fiz-Victor 希望能帮忙测试一下metetor

meteor搜索框的bug复发了，而且还会锁输入法为英文，似乎是自动判别失效了
![image](https://github.com/reserveword/IMBlocker/assets/85837864/e02f96ae-6c0e-49a1-a817-c02adac5c486)
